/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominiummanagement;

import static condominiummanagement.Database.closeConnection;
import static condominiummanagement.Database.conn;
import static condominiummanagement.Database.openConnection;
import static condominiummanagement.Validation.*;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jozhua Ten
 */
public class Payment extends javax.swing.JFrame {
    public static int payment_id = 0;
    private boolean error = false;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        
        // Set default button
        SwingUtilities.getRootPane(btnSearch).setDefaultButton(btnSearch);
    }
    
    // Validate input all inputs and displays their errors (if any)
    private boolean multiValidate() {
        if (!validateUserActivated(txtUserId.getText())) {
            if (!getErrorMessage().equals("")) {
                lblError.setText(getErrorMessage());
            } else {
                lblUserIdError.setText(getUserActivatedErrorMessage());
            }
        }
        if (!validateAmountPaid(txtOutstandingFees.getText(), txtAmountPaid.getText())) {
            lblAmountPaidError.setText(getAmountPaidErrorMessage());
        }
        return (validateUserActivated(txtUserId.getText()) && validateAmountPaid(txtOutstandingFees.getText(), txtAmountPaid.getText()));
    }
    
    // Loads resident's information and return User's Unit ID
    private int loadResident(String user_id) {
        lblError.setText("");
        
        // Calculate outstanding fees
        CalculateFees calculate_fees = new CalculateFees(user_id.toUpperCase());
        if (!calculate_fees.getError()) {
            txtName.setText(calculate_fees.getUserName());
            txtOutstandingFees.setText(String.valueOf(calculate_fees.getOutstandingFees()));
            txtAmountPaid.setText(String.valueOf(calculate_fees.getOutstandingFees()));
            txtAmountPaid.setEditable(true);
            
            txtAmountPaid.requestFocus();
        } else {
            lblError.setText(calculate_fees.getErrorMessage());
        }
        return calculate_fees.getUserUnitId();
    }
    
    // Conduct a payment
    private void payment(String user_id, double amount_paid) {
        // Variables
        error = false;

        lblError.setText("");

        PreparedStatement pay_sql, paymentid_sql;
        ResultSet paymentid_result;
        int userunit_id = loadResident(user_id);

        if (!error && !openConnection()) {
            lblError.setText("Error connecting to database.");
            error = true;
        }
        
        if (!error) {
            try {
                // Insert payment record into database
                pay_sql = conn.prepareStatement("INSERT INTO payment VALUES(NULL, ?, CURRENT_DATE(), ?)");
                pay_sql.setDouble(1, amount_paid);
                pay_sql.setInt(2, userunit_id);
                if (pay_sql.executeUpdate() == 1) {
                    // Get payment record's ID
                    paymentid_sql = conn.prepareStatement("SELECT MAX(Payment_ID) AS Max_ID FROM payment WHERE UserUnit_ID = ? AND Payment_Date = CURRENT_DATE()");
                    paymentid_sql.setInt(1, userunit_id);
                    paymentid_result = paymentid_sql.executeQuery();
                    
                    if (paymentid_result.next()) {
                        payment_id = paymentid_result.getInt("Max_ID");

                        this.dispose();

                        Receipt receipt_form = new Receipt();
                        receipt_form.setVisible(true);
                        receipt_form.setLocationRelativeTo(null);
                    } else {
                        this.dispose();

                        StaffMenu staffmenu_form = new StaffMenu();
                        staffmenu_form.setVisible(true);
                        staffmenu_form.setLocationRelativeTo(null);
                    }
                }
            } catch (SQLException ex) {
                lblError.setText(ex.getMessage());
            } finally {
                if (!closeConnection()) {
                    lblError.setText("Error closing database connection.");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUserId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtOutstandingFees = new javax.swing.JTextField();
        txtAmountPaid = new javax.swing.JTextField();
        lblUserIdError = new javax.swing.JLabel();
        lblAmountPaidError = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(55, 71, 79));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 325));

        txtUserId.setBackground(new java.awt.Color(55, 71, 79));
        txtUserId.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USER ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtUserId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUserId.setPreferredSize(new java.awt.Dimension(250, 50));
        txtUserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserIdFocusLost(evt);
            }
        });
        txtUserId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserIdKeyReleased(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(84, 110, 122));
        btnSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(250, 50));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(55, 71, 79));
        txtName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setPreferredSize(new java.awt.Dimension(250, 50));

        txtOutstandingFees.setEditable(false);
        txtOutstandingFees.setBackground(new java.awt.Color(55, 71, 79));
        txtOutstandingFees.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtOutstandingFees.setForeground(new java.awt.Color(255, 255, 255));
        txtOutstandingFees.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOutstandingFees.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OUTSTANDING FEES (RM)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtOutstandingFees.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOutstandingFees.setPreferredSize(new java.awt.Dimension(250, 50));

        txtAmountPaid.setEditable(false);
        txtAmountPaid.setBackground(new java.awt.Color(55, 71, 79));
        txtAmountPaid.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtAmountPaid.setForeground(new java.awt.Color(255, 255, 255));
        txtAmountPaid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmountPaid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AMOUNT PAID (RM)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAmountPaid.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAmountPaid.setPreferredSize(new java.awt.Dimension(250, 50));
        txtAmountPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountPaidFocusGained(evt);
            }
        });
        txtAmountPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountPaidKeyReleased(evt);
            }
        });

        lblUserIdError.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblUserIdError.setForeground(new java.awt.Color(255, 51, 51));
        lblUserIdError.setPreferredSize(new java.awt.Dimension(250, 20));

        lblAmountPaidError.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblAmountPaidError.setForeground(new java.awt.Color(255, 51, 51));
        lblAmountPaidError.setPreferredSize(new java.awt.Dimension(250, 20));

        btnPay.setBackground(new java.awt.Color(51, 153, 255));
        btnPay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("PAY");
        btnPay.setBorder(null);
        btnPay.setBorderPainted(false);
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.setFocusPainted(false);
        btnPay.setPreferredSize(new java.awt.Dimension(250, 50));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(84, 110, 122));
        btnCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(250, 50));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setPreferredSize(new java.awt.Dimension(250, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOutstandingFees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAmountPaidError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserIdError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAmountPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblUserIdError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtOutstandingFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblAmountPaidError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();

        StaffMenu staffmenu_form = new StaffMenu();
        staffmenu_form.setVisible(true);
        staffmenu_form.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUserIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIdFocusLost
        if (!validateUserActivated(txtUserId.getText())) {
            if (!getErrorMessage().equals("")) {
                lblError.setText(getErrorMessage());
            } else {
                lblUserIdError.setText(getUserActivatedErrorMessage());
            }
        }
    }//GEN-LAST:event_txtUserIdFocusLost

    private void txtUserIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIdKeyPressed
        lblAmountPaidError.setText("");
        lblUserIdError.setText("");
        
        txtOutstandingFees.setText("");
        txtAmountPaid.setText("");
        txtAmountPaid.setEditable(false);
    }//GEN-LAST:event_txtUserIdKeyPressed

    private void txtUserIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIdKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            lblUserIdError.setText("");
        }
    }//GEN-LAST:event_txtUserIdKeyReleased

    private void txtAmountPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountPaidKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            lblAmountPaidError.setText("");
        }
    }//GEN-LAST:event_txtAmountPaidKeyReleased

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (multiValidate()) {
            payment(txtUserId.getText(), Double.parseDouble(txtAmountPaid.getText()));
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        lblAmountPaidError.setText("");
        lblUserIdError.setText("");
        
        txtOutstandingFees.setText("");
        txtAmountPaid.setText("");
        txtAmountPaid.setEditable(false);
        
        if (validateUserActivated(txtUserId.getText())) {
            loadResident(txtUserId.getText());
            txtAmountPaid.requestFocus();
        } else {
            if (!getErrorMessage().equals("")) {
                lblError.setText(getErrorMessage());
            } else {
                lblUserIdError.setText(getUserActivatedErrorMessage());
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAmountPaidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountPaidFocusGained
        // Set default button
        SwingUtilities.getRootPane(btnPay).setDefaultButton(btnPay);
    }//GEN-LAST:event_txtAmountPaidFocusGained

    private void txtUserIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIdFocusGained
        // Set default button
        SwingUtilities.getRootPane(btnSearch).setDefaultButton(btnSearch);
    }//GEN-LAST:event_txtUserIdFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("NimbusLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAmountPaidError;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblUserIdError;
    private javax.swing.JTextField txtAmountPaid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOutstandingFees;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
